export const columns = [
  {
    field: "alias",
    header: "ID",
  },
  {
    field: "alias_subasta",
    header: "SN",
  },
  {
    field: "estado",
    header: "STATUS",
  },
  {
    field: "usuario_nombre",
    header: "AUTHOR",
  },
  {
    field: "primera_publicacion",
    header: "DATE",
  },
  {
    field: "fecha_actualizacion",
    header: "UPDATED",
  },
  {
    field: "tipo_corta",
    header: "Tipo de corta",
  },
  {
    field: "presu_base_impuestos",
    header: "Presupuesto",
    unit: "€",
  },
  {
    field: "volumen_total",
    header: "Cantidad",
    unit: "t",
  },
  {
    field: "volumen_total",
    header: "Tasación unit.",
    unit: "€ / t",
  },
];

export const rows = [
  {
    id: 1,
    alias: "Lote 1",
    calendario_visita: "",
    ccaa: "07",
    certificacion_forestal: "pefc",
    cpv: "3410000",
    estado: "abierto",
    fecha_acuerdo: "10/4/24, 0:00",
    forma_liquidacion: "amedi",
    importe_adjudicacion: 0,
    municipio: "051820",
    objeto_licita: "Lote 1. 675/2022",
    presu_base_impuestos: 6231.1,
    presu_base: 0,
    provincia: "05",
    superficie_ha: 220,
    tipo_corta: "selectiva",
    volumen_total: 17165.6,
    categoria: "publicados",
    alias_subasta: "11846149",
    primera_publicacion: "28/8/23, 7:13",
    fecha_actualizacion: "28/8/23, 7:13",
    fecha_limite_ofertas: "9/9/23, 11:56",
    denominacion_cpv: "Madera",
    requisitos_participa: "",
    fuente_result: "",
    licitacion: "",
    fecha_apertura: "",
    fecha_visita: "",
    fecha_formaliza: "",
    fecha_vigor_contrato: "",
    numero_ofertas: 0,
    precio_inferior: 0,
    precio_superior: 0,
    plazo_ejecucion: "",
    ud_base: "m_cubicos",
    usuario_nombre: "Nemus",
    especies: [
      {
        porcentaje: 50,
        id_tipo_especie: 47,
        nombre: "Pinus pinaster",
      },
      {
        porcentaje: 30,
        id_tipo_especie: 48,
        nombre: "Pinus pinea",
      },
      {
        porcentaje: 20,
        id_tipo_especie: 51,
        nombre: "Pinus sylvestris",
      },
    ],
    numero_expte: "275/2022",
    tipo_contrato: "privado",
    organo_contratacion: "Alcaldia del Ayuntamiento de Pedro Bernardo",
    forma_oferta: "manual",
    visitado: true,
    favorito: false,
    previewImage: "/img/shared/maps/map_small.png",
    especies_summary: "Pinus pinaster, Pinus pinea, Pinus sylvestris",
  },
  {
    id: 9,
    alias: "Lote 9",
    calendario_visita: "",
    ccaa: "07",
    certificacion_forestal: "pefc",
    cpv: "3410000",
    estado: "abierto",
    fecha_acuerdo: "",
    forma_liquidacion: "riesgo",
    importe_adjudicacion: 0,
    municipio: "240515",
    objeto_licita:
      "soto, molino abajo, el prado, valdejindia Poligono 913 Parcela 30",
    presu_base_impuestos: 538597,
    presu_base: 0,
    provincia: "24",
    superficie_ha: 18,
    tipo_corta: "clara",
    volumen_total: 3949.38,
    categoria: "publicados",
    alias_subasta: "11450588",
    primera_publicacion: "28/8/23, 7:13",
    fecha_actualizacion: "28/8/23, 7:13",
    fecha_limite_ofertas: "16/9/23, 14:00",
    denominacion_cpv: "Madera",
    requisitos_participa: "",
    fuente_result: "",
    licitacion: "",
    fecha_apertura: "",
    fecha_visita: "",
    fecha_formaliza: "",
    fecha_vigor_contrato: "",
    numero_ofertas: 0,
    precio_inferior: 0,
    precio_superior: 0,
    plazo_ejecucion: "",
    ud_base: "m_cubicos",
    usuario_nombre: "Nemus",
    especies: [],
    numero_expte: "44593",
    tipo_contrato: "privado",
    organo_contratacion: "Junta Vecinal de Cea",
    forma_oferta: "manual",
    visitado: true,
    favorito: false,
    previewImage: "/img/shared/maps/map_small.png",
    especies_summary: "",
  },
  {
    id: 10,
    alias: "Lote 10",
    calendario_visita: "",
    ccaa: "07",
    certificacion_forestal: "pefc",
    cpv: "3410000",
    estado: "abierto",
    fecha_acuerdo: "",
    forma_liquidacion: "riesgo",
    importe_adjudicacion: 0,
    municipio: "240515",
    objeto_licita:
      "soto, molino abajo, el prado, valdejindia Poligono 913 Parcela 30",
    presu_base_impuestos: 538597,
    presu_base: 0,
    provincia: "24",
    superficie_ha: 18,
    tipo_corta: "clara",
    volumen_total: 3949.38,
    categoria: "publicados",
    alias_subasta: "11450588",
    primera_publicacion: "28/8/23, 7:13",
    fecha_actualizacion: "28/8/23, 7:13",
    fecha_limite_ofertas: "16/9/23, 14:00",
    denominacion_cpv: "Madera",
    requisitos_participa: "",
    fuente_result: "",
    licitacion: "",
    fecha_apertura: "",
    fecha_visita: "",
    fecha_formaliza: "",
    fecha_vigor_contrato: "",
    numero_ofertas: 0,
    precio_inferior: 0,
    precio_superior: 0,
    plazo_ejecucion: "",
    ud_base: "m_cubicos",
    usuario_nombre: "Nemus",
    especies: [],
    numero_expte: "44593",
    tipo_contrato: "privado",
    organo_contratacion: "Junta Vecinal de Cea",
    forma_oferta: "manual",
    visitado: true,
    favorito: false,
    previewImage: "/img/shared/maps/map_small.png",
    especies_summary: "",
  },
  {
    id: 11,
    alias: "Lote 11",
    calendario_visita: "",
    ccaa: "07",
    certificacion_forestal: "pefc",
    cpv: "3410000",
    estado: "abierto",
    fecha_acuerdo: "",
    forma_liquidacion: "riesgo",
    importe_adjudicacion: 0,
    municipio: "240515",
    objeto_licita:
      "soto, molino abajo, el prado, valdejindia Poligono 913 Parcela 30",
    presu_base_impuestos: 538597,
    presu_base: 0,
    provincia: "24",
    superficie_ha: 18,
    tipo_corta: "clara",
    volumen_total: 3949.38,
    categoria: "publicados",
    alias_subasta: "11450588",
    primera_publicacion: "28/8/23, 7:13",
    fecha_actualizacion: "28/8/23, 7:13",
    fecha_limite_ofertas: "16/9/23, 14:00",
    denominacion_cpv: "Madera",
    requisitos_participa: "",
    fuente_result: "",
    licitacion: "",
    fecha_apertura: "",
    fecha_visita: "",
    fecha_formaliza: "",
    fecha_vigor_contrato: "",
    numero_ofertas: 0,
    precio_inferior: 0,
    precio_superior: 0,
    plazo_ejecucion: "",
    ud_base: "m_cubicos",
    usuario_nombre: "Nemus",
    especies: [],
    numero_expte: "44593",
    tipo_contrato: "privado",
    organo_contratacion: "Junta Vecinal de Cea",
    forma_oferta: "manual",
    visitado: true,
    favorito: false,
    previewImage: "/img/shared/maps/map_small.png",
    especies_summary: "",
  },
  {
    id: 12,
    alias: "Lote 12",
    calendario_visita: "",
    ccaa: "07",
    certificacion_forestal: "pefc",
    cpv: "3410000",
    estado: "abierto",
    fecha_acuerdo: "",
    forma_liquidacion: "riesgo",
    importe_adjudicacion: 0,
    municipio: "240515",
    objeto_licita:
      "soto, molino abajo, el prado, valdejindia Poligono 913 Parcela 30",
    presu_base_impuestos: 538597,
    presu_base: 0,
    provincia: "24",
    superficie_ha: 18,
    tipo_corta: "clara",
    volumen_total: 3949.38,
    categoria: "publicados",
    alias_subasta: "11450588",
    primera_publicacion: "28/8/23, 7:13",
    fecha_actualizacion: "28/8/23, 7:13",
    fecha_limite_ofertas: "16/9/23, 14:00",
    denominacion_cpv: "Madera",
    requisitos_participa: "",
    fuente_result: "",
    licitacion: "",
    fecha_apertura: "",
    fecha_visita: "",
    fecha_formaliza: "",
    fecha_vigor_contrato: "",
    numero_ofertas: 0,
    precio_inferior: 0,
    precio_superior: 0,
    plazo_ejecucion: "",
    ud_base: "m_cubicos",
    usuario_nombre: "Nemus",
    especies: [],
    numero_expte: "44593",
    tipo_contrato: "privado",
    organo_contratacion: "Junta Vecinal de Cea",
    forma_oferta: "manual",
    visitado: true,
    favorito: false,
    previewImage: "/img/shared/maps/map_small.png",
    especies_summary: "",
  },
  {
    id: 13,
    alias: "Lote 13",
    calendario_visita: "",
    ccaa: "07",
    certificacion_forestal: "pefc",
    cpv: "3410000",
    estado: "abierto",
    fecha_acuerdo: "",
    forma_liquidacion: "riesgo",
    importe_adjudicacion: 0,
    municipio: "240515",
    objeto_licita:
      "soto, molino abajo, el prado, valdejindia Poligono 913 Parcela 30",
    presu_base_impuestos: 538597,
    presu_base: 0,
    provincia: "24",
    superficie_ha: 18,
    tipo_corta: "clara",
    volumen_total: 3949.38,
    categoria: "publicados",
    alias_subasta: "11450588",
    primera_publicacion: "28/8/23, 7:13",
    fecha_actualizacion: "28/8/23, 7:13",
    fecha_limite_ofertas: "16/9/23, 14:00",
    denominacion_cpv: "Madera",
    requisitos_participa: "",
    fuente_result: "",
    licitacion: "",
    fecha_apertura: "",
    fecha_visita: "",
    fecha_formaliza: "",
    fecha_vigor_contrato: "",
    numero_ofertas: 0,
    precio_inferior: 0,
    precio_superior: 0,
    plazo_ejecucion: "",
    ud_base: "m_cubicos",
    usuario_nombre: "Nemus",
    especies: [],
    numero_expte: "44593",
    tipo_contrato: "privado",
    organo_contratacion: "Junta Vecinal de Cea",
    forma_oferta: "manual",
    visitado: true,
    favorito: false,
    previewImage: "/img/shared/maps/map_small.png",
    especies_summary: "",
  },
  {
    id: 14,
    alias: "Lote 14",
    calendario_visita: "",
    ccaa: "07",
    certificacion_forestal: "pefc",
    cpv: "3410000",
    estado: "abierto",
    fecha_acuerdo: "",
    forma_liquidacion: "riesgo",
    importe_adjudicacion: 0,
    municipio: "240515",
    objeto_licita:
      "soto, molino abajo, el prado, valdejindia Poligono 913 Parcela 30",
    presu_base_impuestos: 538597,
    presu_base: 0,
    provincia: "24",
    superficie_ha: 18,
    tipo_corta: "clara",
    volumen_total: 3949.38,
    categoria: "publicados",
    alias_subasta: "11450588",
    primera_publicacion: "28/8/23, 7:13",
    fecha_actualizacion: "28/8/23, 7:13",
    fecha_limite_ofertas: "16/9/23, 14:00",
    denominacion_cpv: "Madera",
    requisitos_participa: "",
    fuente_result: "",
    licitacion: "",
    fecha_apertura: "",
    fecha_visita: "",
    fecha_formaliza: "",
    fecha_vigor_contrato: "",
    numero_ofertas: 0,
    precio_inferior: 0,
    precio_superior: 0,
    plazo_ejecucion: "",
    ud_base: "m_cubicos",
    usuario_nombre: "Nemus",
    especies: [],
    numero_expte: "44593",
    tipo_contrato: "privado",
    organo_contratacion: "Junta Vecinal de Cea",
    forma_oferta: "manual",
    visitado: true,
    favorito: false,
    previewImage: "/img/shared/maps/map_small.png",
    especies_summary: "",
  },
  {
    id: 15,
    alias: "Lote 15",
    calendario_visita: "",
    ccaa: "07",
    certificacion_forestal: "pefc",
    cpv: "3410000",
    estado: "abierto",
    fecha_acuerdo: "",
    forma_liquidacion: "riesgo",
    importe_adjudicacion: 0,
    municipio: "240515",
    objeto_licita:
      "soto, molino abajo, el prado, valdejindia Poligono 913 Parcela 30",
    presu_base_impuestos: 538597,
    presu_base: 0,
    provincia: "24",
    superficie_ha: 18,
    tipo_corta: "clara",
    volumen_total: 3949.38,
    categoria: "publicados",
    alias_subasta: "11450588",
    primera_publicacion: "28/8/23, 7:13",
    fecha_actualizacion: "28/8/23, 7:13",
    fecha_limite_ofertas: "16/9/23, 14:00",
    denominacion_cpv: "Madera",
    requisitos_participa: "",
    fuente_result: "",
    licitacion: "",
    fecha_apertura: "",
    fecha_visita: "",
    fecha_formaliza: "",
    fecha_vigor_contrato: "",
    numero_ofertas: 0,
    precio_inferior: 0,
    precio_superior: 0,
    plazo_ejecucion: "",
    ud_base: "m_cubicos",
    usuario_nombre: "Nemus",
    especies: [],
    numero_expte: "44593",
    tipo_contrato: "privado",
    organo_contratacion: "Junta Vecinal de Cea",
    forma_oferta: "manual",
    visitado: true,
    favorito: false,
    previewImage: "/img/shared/maps/map_small.png",
    especies_summary: "",
  },
  {
    id: 16,
    alias: "Lote 16",
    calendario_visita: "",
    ccaa: "07",
    certificacion_forestal: "pefc",
    cpv: "3410000",
    estado: "abierto",
    fecha_acuerdo: "",
    forma_liquidacion: "riesgo",
    importe_adjudicacion: 0,
    municipio: "240515",
    objeto_licita:
      "soto, molino abajo, el prado, valdejindia Poligono 913 Parcela 30",
    presu_base_impuestos: 538597,
    presu_base: 0,
    provincia: "24",
    superficie_ha: 18,
    tipo_corta: "clara",
    volumen_total: 3949.38,
    categoria: "publicados",
    alias_subasta: "11450588",
    primera_publicacion: "28/8/23, 7:13",
    fecha_actualizacion: "28/8/23, 7:13",
    fecha_limite_ofertas: "16/9/23, 14:00",
    denominacion_cpv: "Madera",
    requisitos_participa: "",
    fuente_result: "",
    licitacion: "",
    fecha_apertura: "",
    fecha_visita: "",
    fecha_formaliza: "",
    fecha_vigor_contrato: "",
    numero_ofertas: 0,
    precio_inferior: 0,
    precio_superior: 0,
    plazo_ejecucion: "",
    ud_base: "m_cubicos",
    usuario_nombre: "Nemus",
    especies: [],
    numero_expte: "44593",
    tipo_contrato: "privado",
    organo_contratacion: "Junta Vecinal de Cea",
    forma_oferta: "manual",
    visitado: false,
    favorito: false,
    previewImage: "/img/shared/maps/map_small.png",
    especies_summary: "",
  },
  {
    id: 17,
    alias: "Lote 17",
    calendario_visita: "",
    ccaa: "07",
    certificacion_forestal: "pefc",
    cpv: "3410000",
    estado: "abierto",
    fecha_acuerdo: "",
    forma_liquidacion: "riesgo",
    importe_adjudicacion: 0,
    municipio: "240515",
    objeto_licita:
      "soto, molino abajo, el prado, valdejindia Poligono 913 Parcela 30",
    presu_base_impuestos: 538597,
    presu_base: 0,
    provincia: "24",
    superficie_ha: 18,
    tipo_corta: "clara",
    volumen_total: 3949.38,
    categoria: "publicados",
    alias_subasta: "11450588",
    primera_publicacion: "28/8/23, 7:13",
    fecha_actualizacion: "28/8/23, 7:13",
    fecha_limite_ofertas: "16/9/23, 14:00",
    denominacion_cpv: "Madera",
    requisitos_participa: "",
    fuente_result: "",
    licitacion: "",
    fecha_apertura: "",
    fecha_visita: "",
    fecha_formaliza: "",
    fecha_vigor_contrato: "",
    numero_ofertas: 0,
    precio_inferior: 0,
    precio_superior: 0,
    plazo_ejecucion: "",
    ud_base: "m_cubicos",
    usuario_nombre: "Nemus",
    especies: [],
    numero_expte: "44593",
    tipo_contrato: "privado",
    organo_contratacion: "Junta Vecinal de Cea",
    forma_oferta: "manual",
    visitado: false,
    favorito: false,
    previewImage: "/img/shared/maps/map_small.png",
    especies_summary: "",
  },
  {
    id: 18,
    alias: "Lote 18",
    calendario_visita: "",
    ccaa: "07",
    certificacion_forestal: "pefc",
    cpv: "3410000",
    estado: "abierto",
    fecha_acuerdo: "",
    forma_liquidacion: "riesgo",
    importe_adjudicacion: 0,
    municipio: "240515",
    objeto_licita:
      "soto, molino abajo, el prado, valdejindia Poligono 913 Parcela 30",
    presu_base_impuestos: 538597,
    presu_base: 0,
    provincia: "24",
    superficie_ha: 18,
    tipo_corta: "clara",
    volumen_total: 3949.38,
    categoria: "publicados",
    alias_subasta: "11450588",
    primera_publicacion: "28/8/23, 7:13",
    fecha_actualizacion: "28/8/23, 7:13",
    fecha_limite_ofertas: "16/9/23, 14:00",
    denominacion_cpv: "Madera",
    requisitos_participa: "",
    fuente_result: "",
    licitacion: "",
    fecha_apertura: "",
    fecha_visita: "",
    fecha_formaliza: "",
    fecha_vigor_contrato: "",
    numero_ofertas: 0,
    precio_inferior: 0,
    precio_superior: 0,
    plazo_ejecucion: "",
    ud_base: "m_cubicos",
    usuario_nombre: "Nemus",
    especies: [],
    numero_expte: "44593",
    tipo_contrato: "privado",
    organo_contratacion: "Junta Vecinal de Cea",
    forma_oferta: "manual",
    visitado: false,
    favorito: false,
    previewImage: "/img/shared/maps/map_small.png",
    especies_summary: "",
  },
  {
    id: 19,
    alias: "Lote 19",
    calendario_visita: "",
    ccaa: "07",
    certificacion_forestal: "pefc",
    cpv: "3410000",
    estado: "abierto",
    fecha_acuerdo: "",
    forma_liquidacion: "riesgo",
    importe_adjudicacion: 0,
    municipio: "240515",
    objeto_licita:
      "soto, molino abajo, el prado, valdejindia Poligono 913 Parcela 30",
    presu_base_impuestos: 538597,
    presu_base: 0,
    provincia: "24",
    superficie_ha: 18,
    tipo_corta: "clara",
    volumen_total: 3949.38,
    categoria: "publicados",
    alias_subasta: "11450588",
    primera_publicacion: "28/8/23, 7:13",
    fecha_actualizacion: "28/8/23, 7:13",
    fecha_limite_ofertas: "16/9/23, 14:00",
    denominacion_cpv: "Madera",
    requisitos_participa: "",
    fuente_result: "",
    licitacion: "",
    fecha_apertura: "",
    fecha_visita: "",
    fecha_formaliza: "",
    fecha_vigor_contrato: "",
    numero_ofertas: 0,
    precio_inferior: 0,
    precio_superior: 0,
    plazo_ejecucion: "",
    ud_base: "m_cubicos",
    usuario_nombre: "Nemus",
    especies: [],
    numero_expte: "44593",
    tipo_contrato: "privado",
    organo_contratacion: "Junta Vecinal de Cea",
    forma_oferta: "manual",
    visitado: false,
    favorito: false,
    previewImage: "/img/shared/maps/map_small.png",
    especies_summary: "",
  },
  {
    id: 20,
    alias: "Lote 20",
    calendario_visita: "",
    ccaa: "07",
    certificacion_forestal: "pefc",
    cpv: "3410000",
    estado: "abierto",
    fecha_acuerdo: "",
    forma_liquidacion: "riesgo",
    importe_adjudicacion: 0,
    municipio: "240515",
    objeto_licita:
      "soto, molino abajo, el prado, valdejindia Poligono 913 Parcela 30",
    presu_base_impuestos: 538597,
    presu_base: 0,
    provincia: "24",
    superficie_ha: 18,
    tipo_corta: "clara",
    volumen_total: 3949.38,
    categoria: "publicados",
    alias_subasta: "11450588",
    primera_publicacion: "28/8/23, 7:13",
    fecha_actualizacion: "28/8/23, 7:13",
    fecha_limite_ofertas: "16/9/23, 14:00",
    denominacion_cpv: "Madera",
    requisitos_participa: "",
    fuente_result: "",
    licitacion: "",
    fecha_apertura: "",
    fecha_visita: "",
    fecha_formaliza: "",
    fecha_vigor_contrato: "",
    numero_ofertas: 0,
    precio_inferior: 0,
    precio_superior: 0,
    plazo_ejecucion: "",
    ud_base: "m_cubicos",
    usuario_nombre: "Nemus",
    especies: [],
    numero_expte: "44593",
    tipo_contrato: "privado",
    organo_contratacion: "Junta Vecinal de Cea",
    forma_oferta: "manual",
    visitado: false,
    favorito: false,
    previewImage: "/img/shared/maps/map_small.png",
    especies_summary: "",
  },
  {
    id: 21,
    alias: "Lote 21",
    calendario_visita: "",
    ccaa: "07",
    certificacion_forestal: "pefc",
    cpv: "3410000",
    estado: "abierto",
    fecha_acuerdo: "",
    forma_liquidacion: "riesgo",
    importe_adjudicacion: 0,
    municipio: "240515",
    objeto_licita:
      "soto, molino abajo, el prado, valdejindia Poligono 913 Parcela 30",
    presu_base_impuestos: 538597,
    presu_base: 0,
    provincia: "24",
    superficie_ha: 18,
    tipo_corta: "clara",
    volumen_total: 3949.38,
    categoria: "publicados",
    alias_subasta: "11450588",
    primera_publicacion: "28/8/23, 7:13",
    fecha_actualizacion: "28/8/23, 7:13",
    fecha_limite_ofertas: "16/9/23, 14:00",
    denominacion_cpv: "Madera",
    requisitos_participa: "",
    fuente_result: "",
    licitacion: "",
    fecha_apertura: "",
    fecha_visita: "",
    fecha_formaliza: "",
    fecha_vigor_contrato: "",
    numero_ofertas: 0,
    precio_inferior: 0,
    precio_superior: 0,
    plazo_ejecucion: "",
    ud_base: "m_cubicos",
    usuario_nombre: "Nemus",
    especies: [],
    numero_expte: "44593",
    tipo_contrato: "privado",
    organo_contratacion: "Junta Vecinal de Cea",
    forma_oferta: "manual",
    visitado: false,
    favorito: false,
    previewImage: "/img/shared/maps/map_small.png",
    especies_summary: "",
  },
  {
    id: 22,
    alias: "Lote 22",
    calendario_visita: "",
    ccaa: "07",
    certificacion_forestal: "pefc",
    cpv: "3410000",
    estado: "abierto",
    fecha_acuerdo: "",
    forma_liquidacion: "riesgo",
    importe_adjudicacion: 0,
    municipio: "240515",
    objeto_licita:
      "soto, molino abajo, el prado, valdejindia Poligono 913 Parcela 30",
    presu_base_impuestos: 538597,
    presu_base: 0,
    provincia: "24",
    superficie_ha: 18,
    tipo_corta: "clara",
    volumen_total: 3949.38,
    categoria: "publicados",
    alias_subasta: "11450588",
    primera_publicacion: "28/8/23, 7:13",
    fecha_actualizacion: "28/8/23, 7:13",
    fecha_limite_ofertas: "16/9/23, 14:00",
    denominacion_cpv: "Madera",
    requisitos_participa: "",
    fuente_result: "",
    licitacion: "",
    fecha_apertura: "",
    fecha_visita: "",
    fecha_formaliza: "",
    fecha_vigor_contrato: "",
    numero_ofertas: 0,
    precio_inferior: 0,
    precio_superior: 0,
    plazo_ejecucion: "",
    ud_base: "m_cubicos",
    usuario_nombre: "Nemus",
    especies: [],
    numero_expte: "44593",
    tipo_contrato: "privado",
    organo_contratacion: "Junta Vecinal de Cea",
    forma_oferta: "manual",
    visitado: false,
    favorito: false,
    previewImage: "/img/shared/maps/map_small.png",
    especies_summary: "",
  },
  {
    id: 23,
    alias: "Lote 23",
    calendario_visita: "",
    ccaa: "07",
    certificacion_forestal: "pefc",
    cpv: "3410000",
    estado: "abierto",
    fecha_acuerdo: "",
    forma_liquidacion: "riesgo",
    importe_adjudicacion: 0,
    municipio: "240515",
    objeto_licita: "pol 913 par 46",
    presu_base_impuestos: 48578.2,
    presu_base: 0,
    provincia: "24",
    superficie_ha: 2,
    tipo_corta: "clara",
    volumen_total: 362.56,
    categoria: "publicados",
    alias_subasta: "11450588",
    primera_publicacion: "28/8/23, 7:13",
    fecha_actualizacion: "28/8/23, 7:13",
    fecha_limite_ofertas: "16/9/23, 14:00",
    denominacion_cpv: "Madera",
    requisitos_participa: "",
    fuente_result: "",
    licitacion: "",
    fecha_apertura: "",
    fecha_visita: "",
    fecha_formaliza: "",
    fecha_vigor_contrato: "",
    numero_ofertas: 0,
    precio_inferior: 0,
    precio_superior: 0,
    plazo_ejecucion: "",
    ud_base: "m_cubicos",
    usuario_nombre: "Nemus",
    especies: [],
    numero_expte: "44593",
    tipo_contrato: "privado",
    organo_contratacion: "Junta Vecinal de Cea",
    forma_oferta: "manual",
    visitado: false,
    favorito: false,
    previewImage: "/img/shared/maps/map_small.png",
    especies_summary: "",
  },
  {
    id: 24,
    alias: "Lote 24",
    calendario_visita: "",
    ccaa: "",
    certificacion_forestal: "ninguna",
    cpv: "",
    estado: "abierto",
    fecha_acuerdo: "",
    forma_liquidacion: "especificar",
    importe_adjudicacion: 0,
    municipio: "",
    objeto_licita: "qwe",
    presu_base_impuestos: 123,
    presu_base: 123,
    provincia: "",
    superficie_ha: 0,
    tipo_corta: "ordinaria",
    volumen_total: 123,
    categoria: "publicados",
    alias_subasta: "11846149",
    primera_publicacion: "28/8/23, 7:13",
    fecha_actualizacion: "28/8/23, 7:13",
    fecha_limite_ofertas: "9/9/23, 11:56",
    denominacion_cpv: "",
    requisitos_participa: "",
    fuente_result: "",
    licitacion: "",
    fecha_apertura: "",
    fecha_visita: "",
    fecha_formaliza: "",
    fecha_vigor_contrato: "",
    numero_ofertas: 0,
    precio_inferior: 0,
    precio_superior: 0,
    plazo_ejecucion: "",
    ud_base: "",
    usuario_nombre: "Luis",
    especies: [],
    numero_expte: "275/2022",
    tipo_contrato: "privado",
    organo_contratacion: "Alcaldia del Ayuntamiento de Pedro Bernardo",
    forma_oferta: "manual",
    visitado: true,
    favorito: false,
    previewImage: "/img/shared/maps/map_small.png",
    especies_summary: "",
  },
  {
    id: 25,
    alias: "Lote 25",
    calendario_visita: "",
    ccaa: "",
    certificacion_forestal: "ninguna",
    cpv: "",
    estado: "abierto",
    fecha_acuerdo: "",
    forma_liquidacion: "especificar",
    importe_adjudicacion: 0,
    municipio: "",
    objeto_licita: "qweqweq",
    presu_base_impuestos: 21231,
    presu_base: 12321200,
    provincia: "",
    superficie_ha: 0,
    tipo_corta: "ordinaria",
    volumen_total: 123123,
    categoria: "publicados",
    alias_subasta: "11846149",
    primera_publicacion: "28/8/23, 7:13",
    fecha_actualizacion: "28/8/23, 7:13",
    fecha_limite_ofertas: "9/9/23, 11:56",
    denominacion_cpv: "",
    requisitos_participa: "",
    fuente_result: "",
    licitacion: "",
    fecha_apertura: "",
    fecha_visita: "",
    fecha_formaliza: "",
    fecha_vigor_contrato: "",
    numero_ofertas: 0,
    precio_inferior: 0,
    precio_superior: 0,
    plazo_ejecucion: "",
    ud_base: "",
    usuario_nombre: "Luis",
    especies: [],
    numero_expte: "275/2022",
    tipo_contrato: "privado",
    organo_contratacion: "Alcaldia del Ayuntamiento de Pedro Bernardo",
    forma_oferta: "manual",
    visitado: false,
    favorito: false,
    previewImage: "/img/shared/maps/map_small.png",
    especies_summary: "",
  },
  {
    id: 26,
    alias: "Lote 26",
    calendario_visita: "",
    ccaa: "",
    certificacion_forestal: "ninguna",
    cpv: "",
    estado: "abierto",
    fecha_acuerdo: "",
    forma_liquidacion: "especificar",
    importe_adjudicacion: 0,
    municipio: "",
    objeto_licita: "qweqwe",
    presu_base_impuestos: 123,
    presu_base: 123,
    provincia: "",
    superficie_ha: 0,
    tipo_corta: "ordinaria",
    volumen_total: 123,
    categoria: "publicados",
    alias_subasta: "11846149",
    primera_publicacion: "28/8/23, 7:13",
    fecha_actualizacion: "28/8/23, 7:13",
    fecha_limite_ofertas: "9/9/23, 11:56",
    denominacion_cpv: "",
    requisitos_participa: "",
    fuente_result: "",
    licitacion: "",
    fecha_apertura: "",
    fecha_visita: "",
    fecha_formaliza: "",
    fecha_vigor_contrato: "",
    numero_ofertas: 0,
    precio_inferior: 0,
    precio_superior: 0,
    plazo_ejecucion: "",
    ud_base: "",
    usuario_nombre: "Luis",
    especies: [],
    numero_expte: "275/2022",
    tipo_contrato: "privado",
    organo_contratacion: "Alcaldia del Ayuntamiento de Pedro Bernardo",
    forma_oferta: "manual",
    visitado: false,
    favorito: false,
    previewImage: "/img/shared/maps/map_small.png",
    especies_summary: "",
  },
  {
    id: 1,
    alias: "Lote 1",
    calendario_visita: "",
    ccaa: "07",
    certificacion_forestal: "pefc",
    cpv: "3410000",
    estado: "abierto",
    fecha_acuerdo: "10/4/24, 0:00",
    forma_liquidacion: "amedi",
    importe_adjudicacion: 0,
    municipio: "051820",
    objeto_licita: "Lote 1. 675/2022",
    presu_base_impuestos: 6231.1,
    presu_base: 0,
    provincia: "05",
    superficie_ha: 220,
    tipo_corta: "selectiva",
    volumen_total: 17165.6,
    categoria: "publicados",
    alias_subasta: "11846149",
    primera_publicacion: "28/8/23, 7:13",
    fecha_actualizacion: "28/8/23, 7:13",
    fecha_limite_ofertas: "9/9/23, 11:56",
    denominacion_cpv: "Madera",
    requisitos_participa: "",
    fuente_result: "",
    licitacion: "",
    fecha_apertura: "",
    fecha_visita: "",
    fecha_formaliza: "",
    fecha_vigor_contrato: "",
    numero_ofertas: 0,
    precio_inferior: 0,
    precio_superior: 0,
    plazo_ejecucion: "",
    ud_base: "m_cubicos",
    usuario_nombre: "Nemus",
    especies: [
      {
        porcentaje: 50,
        id_tipo_especie: 47,
        nombre: "Pinus pinaster",
      },
      {
        porcentaje: 30,
        id_tipo_especie: 48,
        nombre: "Pinus pinea",
      },
      {
        porcentaje: 20,
        id_tipo_especie: 51,
        nombre: "Pinus sylvestris",
      },
    ],
    numero_expte: "275/2022",
    tipo_contrato: "privado",
    organo_contratacion: "Alcaldia del Ayuntamiento de Pedro Bernardo",
    forma_oferta: "manual",
    visitado: true,
    favorito: false,
    previewImage: "/img/shared/maps/map_small.png",
    especies_summary: "Pinus pinaster, Pinus pinea, Pinus sylvestris",
  },
  {
    id: 9,
    alias: "Lote 9",
    calendario_visita: "",
    ccaa: "07",
    certificacion_forestal: "pefc",
    cpv: "3410000",
    estado: "abierto",
    fecha_acuerdo: "",
    forma_liquidacion: "riesgo",
    importe_adjudicacion: 0,
    municipio: "240515",
    objeto_licita:
      "soto, molino abajo, el prado, valdejindia Poligono 913 Parcela 30",
    presu_base_impuestos: 538597,
    presu_base: 0,
    provincia: "24",
    superficie_ha: 18,
    tipo_corta: "clara",
    volumen_total: 3949.38,
    categoria: "publicados",
    alias_subasta: "11450588",
    primera_publicacion: "28/8/23, 7:13",
    fecha_actualizacion: "28/8/23, 7:13",
    fecha_limite_ofertas: "16/9/23, 14:00",
    denominacion_cpv: "Madera",
    requisitos_participa: "",
    fuente_result: "",
    licitacion: "",
    fecha_apertura: "",
    fecha_visita: "",
    fecha_formaliza: "",
    fecha_vigor_contrato: "",
    numero_ofertas: 0,
    precio_inferior: 0,
    precio_superior: 0,
    plazo_ejecucion: "",
    ud_base: "m_cubicos",
    usuario_nombre: "Nemus",
    especies: [],
    numero_expte: "44593",
    tipo_contrato: "privado",
    organo_contratacion: "Junta Vecinal de Cea",
    forma_oferta: "manual",
    visitado: true,
    favorito: false,
    previewImage: "/img/shared/maps/map_small.png",
    especies_summary: "",
  },
  {
    id: 10,
    alias: "Lote 10",
    calendario_visita: "",
    ccaa: "07",
    certificacion_forestal: "pefc",
    cpv: "3410000",
    estado: "abierto",
    fecha_acuerdo: "",
    forma_liquidacion: "riesgo",
    importe_adjudicacion: 0,
    municipio: "240515",
    objeto_licita:
      "soto, molino abajo, el prado, valdejindia Poligono 913 Parcela 30",
    presu_base_impuestos: 538597,
    presu_base: 0,
    provincia: "24",
    superficie_ha: 18,
    tipo_corta: "clara",
    volumen_total: 3949.38,
    categoria: "publicados",
    alias_subasta: "11450588",
    primera_publicacion: "28/8/23, 7:13",
    fecha_actualizacion: "28/8/23, 7:13",
    fecha_limite_ofertas: "16/9/23, 14:00",
    denominacion_cpv: "Madera",
    requisitos_participa: "",
    fuente_result: "",
    licitacion: "",
    fecha_apertura: "",
    fecha_visita: "",
    fecha_formaliza: "",
    fecha_vigor_contrato: "",
    numero_ofertas: 0,
    precio_inferior: 0,
    precio_superior: 0,
    plazo_ejecucion: "",
    ud_base: "m_cubicos",
    usuario_nombre: "Nemus",
    especies: [],
    numero_expte: "44593",
    tipo_contrato: "privado",
    organo_contratacion: "Junta Vecinal de Cea",
    forma_oferta: "manual",
    visitado: true,
    favorito: false,
    previewImage: "/img/shared/maps/map_small.png",
    especies_summary: "",
  },
  {
    id: 11,
    alias: "Lote 11",
    calendario_visita: "",
    ccaa: "07",
    certificacion_forestal: "pefc",
    cpv: "3410000",
    estado: "abierto",
    fecha_acuerdo: "",
    forma_liquidacion: "riesgo",
    importe_adjudicacion: 0,
    municipio: "240515",
    objeto_licita:
      "soto, molino abajo, el prado, valdejindia Poligono 913 Parcela 30",
    presu_base_impuestos: 538597,
    presu_base: 0,
    provincia: "24",
    superficie_ha: 18,
    tipo_corta: "clara",
    volumen_total: 3949.38,
    categoria: "publicados",
    alias_subasta: "11450588",
    primera_publicacion: "28/8/23, 7:13",
    fecha_actualizacion: "28/8/23, 7:13",
    fecha_limite_ofertas: "16/9/23, 14:00",
    denominacion_cpv: "Madera",
    requisitos_participa: "",
    fuente_result: "",
    licitacion: "",
    fecha_apertura: "",
    fecha_visita: "",
    fecha_formaliza: "",
    fecha_vigor_contrato: "",
    numero_ofertas: 0,
    precio_inferior: 0,
    precio_superior: 0,
    plazo_ejecucion: "",
    ud_base: "m_cubicos",
    usuario_nombre: "Nemus",
    especies: [],
    numero_expte: "44593",
    tipo_contrato: "privado",
    organo_contratacion: "Junta Vecinal de Cea",
    forma_oferta: "manual",
    visitado: true,
    favorito: false,
    previewImage: "/img/shared/maps/map_small.png",
    especies_summary: "",
  },
  {
    id: 12,
    alias: "Lote 12",
    calendario_visita: "",
    ccaa: "07",
    certificacion_forestal: "pefc",
    cpv: "3410000",
    estado: "abierto",
    fecha_acuerdo: "",
    forma_liquidacion: "riesgo",
    importe_adjudicacion: 0,
    municipio: "240515",
    objeto_licita:
      "soto, molino abajo, el prado, valdejindia Poligono 913 Parcela 30",
    presu_base_impuestos: 538597,
    presu_base: 0,
    provincia: "24",
    superficie_ha: 18,
    tipo_corta: "clara",
    volumen_total: 3949.38,
    categoria: "publicados",
    alias_subasta: "11450588",
    primera_publicacion: "28/8/23, 7:13",
    fecha_actualizacion: "28/8/23, 7:13",
    fecha_limite_ofertas: "16/9/23, 14:00",
    denominacion_cpv: "Madera",
    requisitos_participa: "",
    fuente_result: "",
    licitacion: "",
    fecha_apertura: "",
    fecha_visita: "",
    fecha_formaliza: "",
    fecha_vigor_contrato: "",
    numero_ofertas: 0,
    precio_inferior: 0,
    precio_superior: 0,
    plazo_ejecucion: "",
    ud_base: "m_cubicos",
    usuario_nombre: "Nemus",
    especies: [],
    numero_expte: "44593",
    tipo_contrato: "privado",
    organo_contratacion: "Junta Vecinal de Cea",
    forma_oferta: "manual",
    visitado: true,
    favorito: false,
    previewImage: "/img/shared/maps/map_small.png",
    especies_summary: "",
  },
  {
    id: 13,
    alias: "Lote 13",
    calendario_visita: "",
    ccaa: "07",
    certificacion_forestal: "pefc",
    cpv: "3410000",
    estado: "abierto",
    fecha_acuerdo: "",
    forma_liquidacion: "riesgo",
    importe_adjudicacion: 0,
    municipio: "240515",
    objeto_licita:
      "soto, molino abajo, el prado, valdejindia Poligono 913 Parcela 30",
    presu_base_impuestos: 538597,
    presu_base: 0,
    provincia: "24",
    superficie_ha: 18,
    tipo_corta: "clara",
    volumen_total: 3949.38,
    categoria: "publicados",
    alias_subasta: "11450588",
    primera_publicacion: "28/8/23, 7:13",
    fecha_actualizacion: "28/8/23, 7:13",
    fecha_limite_ofertas: "16/9/23, 14:00",
    denominacion_cpv: "Madera",
    requisitos_participa: "",
    fuente_result: "",
    licitacion: "",
    fecha_apertura: "",
    fecha_visita: "",
    fecha_formaliza: "",
    fecha_vigor_contrato: "",
    numero_ofertas: 0,
    precio_inferior: 0,
    precio_superior: 0,
    plazo_ejecucion: "",
    ud_base: "m_cubicos",
    usuario_nombre: "Nemus",
    especies: [],
    numero_expte: "44593",
    tipo_contrato: "privado",
    organo_contratacion: "Junta Vecinal de Cea",
    forma_oferta: "manual",
    visitado: true,
    favorito: false,
    previewImage: "/img/shared/maps/map_small.png",
    especies_summary: "",
  },
  {
    id: 14,
    alias: "Lote 14",
    calendario_visita: "",
    ccaa: "07",
    certificacion_forestal: "pefc",
    cpv: "3410000",
    estado: "abierto",
    fecha_acuerdo: "",
    forma_liquidacion: "riesgo",
    importe_adjudicacion: 0,
    municipio: "240515",
    objeto_licita:
      "soto, molino abajo, el prado, valdejindia Poligono 913 Parcela 30",
    presu_base_impuestos: 538597,
    presu_base: 0,
    provincia: "24",
    superficie_ha: 18,
    tipo_corta: "clara",
    volumen_total: 3949.38,
    categoria: "publicados",
    alias_subasta: "11450588",
    primera_publicacion: "28/8/23, 7:13",
    fecha_actualizacion: "28/8/23, 7:13",
    fecha_limite_ofertas: "16/9/23, 14:00",
    denominacion_cpv: "Madera",
    requisitos_participa: "",
    fuente_result: "",
    licitacion: "",
    fecha_apertura: "",
    fecha_visita: "",
    fecha_formaliza: "",
    fecha_vigor_contrato: "",
    numero_ofertas: 0,
    precio_inferior: 0,
    precio_superior: 0,
    plazo_ejecucion: "",
    ud_base: "m_cubicos",
    usuario_nombre: "Nemus",
    especies: [],
    numero_expte: "44593",
    tipo_contrato: "privado",
    organo_contratacion: "Junta Vecinal de Cea",
    forma_oferta: "manual",
    visitado: true,
    favorito: false,
    previewImage: "/img/shared/maps/map_small.png",
    especies_summary: "",
  },
  {
    id: 15,
    alias: "Lote 15",
    calendario_visita: "",
    ccaa: "07",
    certificacion_forestal: "pefc",
    cpv: "3410000",
    estado: "abierto",
    fecha_acuerdo: "",
    forma_liquidacion: "riesgo",
    importe_adjudicacion: 0,
    municipio: "240515",
    objeto_licita:
      "soto, molino abajo, el prado, valdejindia Poligono 913 Parcela 30",
    presu_base_impuestos: 538597,
    presu_base: 0,
    provincia: "24",
    superficie_ha: 18,
    tipo_corta: "clara",
    volumen_total: 3949.38,
    categoria: "publicados",
    alias_subasta: "11450588",
    primera_publicacion: "28/8/23, 7:13",
    fecha_actualizacion: "28/8/23, 7:13",
    fecha_limite_ofertas: "16/9/23, 14:00",
    denominacion_cpv: "Madera",
    requisitos_participa: "",
    fuente_result: "",
    licitacion: "",
    fecha_apertura: "",
    fecha_visita: "",
    fecha_formaliza: "",
    fecha_vigor_contrato: "",
    numero_ofertas: 0,
    precio_inferior: 0,
    precio_superior: 0,
    plazo_ejecucion: "",
    ud_base: "m_cubicos",
    usuario_nombre: "Nemus",
    especies: [],
    numero_expte: "44593",
    tipo_contrato: "privado",
    organo_contratacion: "Junta Vecinal de Cea",
    forma_oferta: "manual",
    visitado: true,
    favorito: false,
    previewImage: "/img/shared/maps/map_small.png",
    especies_summary: "",
  },
  {
    id: 16,
    alias: "Lote 16",
    calendario_visita: "",
    ccaa: "07",
    certificacion_forestal: "pefc",
    cpv: "3410000",
    estado: "abierto",
    fecha_acuerdo: "",
    forma_liquidacion: "riesgo",
    importe_adjudicacion: 0,
    municipio: "240515",
    objeto_licita:
      "soto, molino abajo, el prado, valdejindia Poligono 913 Parcela 30",
    presu_base_impuestos: 538597,
    presu_base: 0,
    provincia: "24",
    superficie_ha: 18,
    tipo_corta: "clara",
    volumen_total: 3949.38,
    categoria: "publicados",
    alias_subasta: "11450588",
    primera_publicacion: "28/8/23, 7:13",
    fecha_actualizacion: "28/8/23, 7:13",
    fecha_limite_ofertas: "16/9/23, 14:00",
    denominacion_cpv: "Madera",
    requisitos_participa: "",
    fuente_result: "",
    licitacion: "",
    fecha_apertura: "",
    fecha_visita: "",
    fecha_formaliza: "",
    fecha_vigor_contrato: "",
    numero_ofertas: 0,
    precio_inferior: 0,
    precio_superior: 0,
    plazo_ejecucion: "",
    ud_base: "m_cubicos",
    usuario_nombre: "Nemus",
    especies: [],
    numero_expte: "44593",
    tipo_contrato: "privado",
    organo_contratacion: "Junta Vecinal de Cea",
    forma_oferta: "manual",
    visitado: false,
    favorito: false,
    previewImage: "/img/shared/maps/map_small.png",
    especies_summary: "",
  },
  {
    id: 17,
    alias: "Lote 17",
    calendario_visita: "",
    ccaa: "07",
    certificacion_forestal: "pefc",
    cpv: "3410000",
    estado: "abierto",
    fecha_acuerdo: "",
    forma_liquidacion: "riesgo",
    importe_adjudicacion: 0,
    municipio: "240515",
    objeto_licita:
      "soto, molino abajo, el prado, valdejindia Poligono 913 Parcela 30",
    presu_base_impuestos: 538597,
    presu_base: 0,
    provincia: "24",
    superficie_ha: 18,
    tipo_corta: "clara",
    volumen_total: 3949.38,
    categoria: "publicados",
    alias_subasta: "11450588",
    primera_publicacion: "28/8/23, 7:13",
    fecha_actualizacion: "28/8/23, 7:13",
    fecha_limite_ofertas: "16/9/23, 14:00",
    denominacion_cpv: "Madera",
    requisitos_participa: "",
    fuente_result: "",
    licitacion: "",
    fecha_apertura: "",
    fecha_visita: "",
    fecha_formaliza: "",
    fecha_vigor_contrato: "",
    numero_ofertas: 0,
    precio_inferior: 0,
    precio_superior: 0,
    plazo_ejecucion: "",
    ud_base: "m_cubicos",
    usuario_nombre: "Nemus",
    especies: [],
    numero_expte: "44593",
    tipo_contrato: "privado",
    organo_contratacion: "Junta Vecinal de Cea",
    forma_oferta: "manual",
    visitado: false,
    favorito: false,
    previewImage: "/img/shared/maps/map_small.png",
    especies_summary: "",
  },
  {
    id: 18,
    alias: "Lote 18",
    calendario_visita: "",
    ccaa: "07",
    certificacion_forestal: "pefc",
    cpv: "3410000",
    estado: "abierto",
    fecha_acuerdo: "",
    forma_liquidacion: "riesgo",
    importe_adjudicacion: 0,
    municipio: "240515",
    objeto_licita:
      "soto, molino abajo, el prado, valdejindia Poligono 913 Parcela 30",
    presu_base_impuestos: 538597,
    presu_base: 0,
    provincia: "24",
    superficie_ha: 18,
    tipo_corta: "clara",
    volumen_total: 3949.38,
    categoria: "publicados",
    alias_subasta: "11450588",
    primera_publicacion: "28/8/23, 7:13",
    fecha_actualizacion: "28/8/23, 7:13",
    fecha_limite_ofertas: "16/9/23, 14:00",
    denominacion_cpv: "Madera",
    requisitos_participa: "",
    fuente_result: "",
    licitacion: "",
    fecha_apertura: "",
    fecha_visita: "",
    fecha_formaliza: "",
    fecha_vigor_contrato: "",
    numero_ofertas: 0,
    precio_inferior: 0,
    precio_superior: 0,
    plazo_ejecucion: "",
    ud_base: "m_cubicos",
    usuario_nombre: "Nemus",
    especies: [],
    numero_expte: "44593",
    tipo_contrato: "privado",
    organo_contratacion: "Junta Vecinal de Cea",
    forma_oferta: "manual",
    visitado: false,
    favorito: false,
    previewImage: "/img/shared/maps/map_small.png",
    especies_summary: "",
  },
  {
    id: 19,
    alias: "Lote 19",
    calendario_visita: "",
    ccaa: "07",
    certificacion_forestal: "pefc",
    cpv: "3410000",
    estado: "abierto",
    fecha_acuerdo: "",
    forma_liquidacion: "riesgo",
    importe_adjudicacion: 0,
    municipio: "240515",
    objeto_licita:
      "soto, molino abajo, el prado, valdejindia Poligono 913 Parcela 30",
    presu_base_impuestos: 538597,
    presu_base: 0,
    provincia: "24",
    superficie_ha: 18,
    tipo_corta: "clara",
    volumen_total: 3949.38,
    categoria: "publicados",
    alias_subasta: "11450588",
    primera_publicacion: "28/8/23, 7:13",
    fecha_actualizacion: "28/8/23, 7:13",
    fecha_limite_ofertas: "16/9/23, 14:00",
    denominacion_cpv: "Madera",
    requisitos_participa: "",
    fuente_result: "",
    licitacion: "",
    fecha_apertura: "",
    fecha_visita: "",
    fecha_formaliza: "",
    fecha_vigor_contrato: "",
    numero_ofertas: 0,
    precio_inferior: 0,
    precio_superior: 0,
    plazo_ejecucion: "",
    ud_base: "m_cubicos",
    usuario_nombre: "Nemus",
    especies: [],
    numero_expte: "44593",
    tipo_contrato: "privado",
    organo_contratacion: "Junta Vecinal de Cea",
    forma_oferta: "manual",
    visitado: false,
    favorito: false,
    previewImage: "/img/shared/maps/map_small.png",
    especies_summary: "",
  },
  {
    id: 20,
    alias: "Lote 20",
    calendario_visita: "",
    ccaa: "07",
    certificacion_forestal: "pefc",
    cpv: "3410000",
    estado: "abierto",
    fecha_acuerdo: "",
    forma_liquidacion: "riesgo",
    importe_adjudicacion: 0,
    municipio: "240515",
    objeto_licita:
      "soto, molino abajo, el prado, valdejindia Poligono 913 Parcela 30",
    presu_base_impuestos: 538597,
    presu_base: 0,
    provincia: "24",
    superficie_ha: 18,
    tipo_corta: "clara",
    volumen_total: 3949.38,
    categoria: "publicados",
    alias_subasta: "11450588",
    primera_publicacion: "28/8/23, 7:13",
    fecha_actualizacion: "28/8/23, 7:13",
    fecha_limite_ofertas: "16/9/23, 14:00",
    denominacion_cpv: "Madera",
    requisitos_participa: "",
    fuente_result: "",
    licitacion: "",
    fecha_apertura: "",
    fecha_visita: "",
    fecha_formaliza: "",
    fecha_vigor_contrato: "",
    numero_ofertas: 0,
    precio_inferior: 0,
    precio_superior: 0,
    plazo_ejecucion: "",
    ud_base: "m_cubicos",
    usuario_nombre: "Nemus",
    especies: [],
    numero_expte: "44593",
    tipo_contrato: "privado",
    organo_contratacion: "Junta Vecinal de Cea",
    forma_oferta: "manual",
    visitado: false,
    favorito: false,
    previewImage: "/img/shared/maps/map_small.png",
    especies_summary: "",
  },
  {
    id: 21,
    alias: "Lote 21",
    calendario_visita: "",
    ccaa: "07",
    certificacion_forestal: "pefc",
    cpv: "3410000",
    estado: "abierto",
    fecha_acuerdo: "",
    forma_liquidacion: "riesgo",
    importe_adjudicacion: 0,
    municipio: "240515",
    objeto_licita:
      "soto, molino abajo, el prado, valdejindia Poligono 913 Parcela 30",
    presu_base_impuestos: 538597,
    presu_base: 0,
    provincia: "24",
    superficie_ha: 18,
    tipo_corta: "clara",
    volumen_total: 3949.38,
    categoria: "publicados",
    alias_subasta: "11450588",
    primera_publicacion: "28/8/23, 7:13",
    fecha_actualizacion: "28/8/23, 7:13",
    fecha_limite_ofertas: "16/9/23, 14:00",
    denominacion_cpv: "Madera",
    requisitos_participa: "",
    fuente_result: "",
    licitacion: "",
    fecha_apertura: "",
    fecha_visita: "",
    fecha_formaliza: "",
    fecha_vigor_contrato: "",
    numero_ofertas: 0,
    precio_inferior: 0,
    precio_superior: 0,
    plazo_ejecucion: "",
    ud_base: "m_cubicos",
    usuario_nombre: "Nemus",
    especies: [],
    numero_expte: "44593",
    tipo_contrato: "privado",
    organo_contratacion: "Junta Vecinal de Cea",
    forma_oferta: "manual",
    visitado: false,
    favorito: false,
    previewImage: "/img/shared/maps/map_small.png",
    especies_summary: "",
  },
  {
    id: 22,
    alias: "Lote 22",
    calendario_visita: "",
    ccaa: "07",
    certificacion_forestal: "pefc",
    cpv: "3410000",
    estado: "abierto",
    fecha_acuerdo: "",
    forma_liquidacion: "riesgo",
    importe_adjudicacion: 0,
    municipio: "240515",
    objeto_licita:
      "soto, molino abajo, el prado, valdejindia Poligono 913 Parcela 30",
    presu_base_impuestos: 538597,
    presu_base: 0,
    provincia: "24",
    superficie_ha: 18,
    tipo_corta: "clara",
    volumen_total: 3949.38,
    categoria: "publicados",
    alias_subasta: "11450588",
    primera_publicacion: "28/8/23, 7:13",
    fecha_actualizacion: "28/8/23, 7:13",
    fecha_limite_ofertas: "16/9/23, 14:00",
    denominacion_cpv: "Madera",
    requisitos_participa: "",
    fuente_result: "",
    licitacion: "",
    fecha_apertura: "",
    fecha_visita: "",
    fecha_formaliza: "",
    fecha_vigor_contrato: "",
    numero_ofertas: 0,
    precio_inferior: 0,
    precio_superior: 0,
    plazo_ejecucion: "",
    ud_base: "m_cubicos",
    usuario_nombre: "Nemus",
    especies: [],
    numero_expte: "44593",
    tipo_contrato: "privado",
    organo_contratacion: "Junta Vecinal de Cea",
    forma_oferta: "manual",
    visitado: false,
    favorito: false,
    previewImage: "/img/shared/maps/map_small.png",
    especies_summary: "",
  },
  {
    id: 23,
    alias: "Lote 23",
    calendario_visita: "",
    ccaa: "07",
    certificacion_forestal: "pefc",
    cpv: "3410000",
    estado: "abierto",
    fecha_acuerdo: "",
    forma_liquidacion: "riesgo",
    importe_adjudicacion: 0,
    municipio: "240515",
    objeto_licita: "pol 913 par 46",
    presu_base_impuestos: 48578.2,
    presu_base: 0,
    provincia: "24",
    superficie_ha: 2,
    tipo_corta: "clara",
    volumen_total: 362.56,
    categoria: "publicados",
    alias_subasta: "11450588",
    primera_publicacion: "28/8/23, 7:13",
    fecha_actualizacion: "28/8/23, 7:13",
    fecha_limite_ofertas: "16/9/23, 14:00",
    denominacion_cpv: "Madera",
    requisitos_participa: "",
    fuente_result: "",
    licitacion: "",
    fecha_apertura: "",
    fecha_visita: "",
    fecha_formaliza: "",
    fecha_vigor_contrato: "",
    numero_ofertas: 0,
    precio_inferior: 0,
    precio_superior: 0,
    plazo_ejecucion: "",
    ud_base: "m_cubicos",
    usuario_nombre: "Nemus",
    especies: [],
    numero_expte: "44593",
    tipo_contrato: "privado",
    organo_contratacion: "Junta Vecinal de Cea",
    forma_oferta: "manual",
    visitado: false,
    favorito: false,
    previewImage: "/img/shared/maps/map_small.png",
    especies_summary: "",
  },
  {
    id: 24,
    alias: "Lote 24",
    calendario_visita: "",
    ccaa: "",
    certificacion_forestal: "ninguna",
    cpv: "",
    estado: "abierto",
    fecha_acuerdo: "",
    forma_liquidacion: "especificar",
    importe_adjudicacion: 0,
    municipio: "",
    objeto_licita: "qwe",
    presu_base_impuestos: 123,
    presu_base: 123,
    provincia: "",
    superficie_ha: 0,
    tipo_corta: "ordinaria",
    volumen_total: 123,
    categoria: "publicados",
    alias_subasta: "11846149",
    primera_publicacion: "28/8/23, 7:13",
    fecha_actualizacion: "28/8/23, 7:13",
    fecha_limite_ofertas: "9/9/23, 11:56",
    denominacion_cpv: "",
    requisitos_participa: "",
    fuente_result: "",
    licitacion: "",
    fecha_apertura: "",
    fecha_visita: "",
    fecha_formaliza: "",
    fecha_vigor_contrato: "",
    numero_ofertas: 0,
    precio_inferior: 0,
    precio_superior: 0,
    plazo_ejecucion: "",
    ud_base: "",
    usuario_nombre: "Luis",
    especies: [],
    numero_expte: "275/2022",
    tipo_contrato: "privado",
    organo_contratacion: "Alcaldia del Ayuntamiento de Pedro Bernardo",
    forma_oferta: "manual",
    visitado: true,
    favorito: false,
    previewImage: "/img/shared/maps/map_small.png",
    especies_summary: "",
  },
  {
    id: 25,
    alias: "Lote 25",
    calendario_visita: "",
    ccaa: "",
    certificacion_forestal: "ninguna",
    cpv: "",
    estado: "abierto",
    fecha_acuerdo: "",
    forma_liquidacion: "especificar",
    importe_adjudicacion: 0,
    municipio: "",
    objeto_licita: "qweqweq",
    presu_base_impuestos: 21231,
    presu_base: 12321200,
    provincia: "",
    superficie_ha: 0,
    tipo_corta: "ordinaria",
    volumen_total: 123123,
    categoria: "publicados",
    alias_subasta: "11846149",
    primera_publicacion: "28/8/23, 7:13",
    fecha_actualizacion: "28/8/23, 7:13",
    fecha_limite_ofertas: "9/9/23, 11:56",
    denominacion_cpv: "",
    requisitos_participa: "",
    fuente_result: "",
    licitacion: "",
    fecha_apertura: "",
    fecha_visita: "",
    fecha_formaliza: "",
    fecha_vigor_contrato: "",
    numero_ofertas: 0,
    precio_inferior: 0,
    precio_superior: 0,
    plazo_ejecucion: "",
    ud_base: "",
    usuario_nombre: "Luis",
    especies: [],
    numero_expte: "275/2022",
    tipo_contrato: "privado",
    organo_contratacion: "Alcaldia del Ayuntamiento de Pedro Bernardo",
    forma_oferta: "manual",
    visitado: false,
    favorito: false,
    previewImage: "/img/shared/maps/map_small.png",
    especies_summary: "",
  },
  {
    id: 26,
    alias: "Lote 26",
    calendario_visita: "",
    ccaa: "",
    certificacion_forestal: "ninguna",
    cpv: "",
    estado: "abierto",
    fecha_acuerdo: "",
    forma_liquidacion: "especificar",
    importe_adjudicacion: 0,
    municipio: "",
    objeto_licita: "qweqwe",
    presu_base_impuestos: 123,
    presu_base: 123,
    provincia: "",
    superficie_ha: 0,
    tipo_corta: "ordinaria",
    volumen_total: 123,
    categoria: "publicados",
    alias_subasta: "11846149",
    primera_publicacion: "28/8/23, 7:13",
    fecha_actualizacion: "28/8/23, 7:13",
    fecha_limite_ofertas: "9/9/23, 11:56",
    denominacion_cpv: "",
    requisitos_participa: "",
    fuente_result: "",
    licitacion: "",
    fecha_apertura: "",
    fecha_visita: "",
    fecha_formaliza: "",
    fecha_vigor_contrato: "",
    numero_ofertas: 0,
    precio_inferior: 0,
    precio_superior: 0,
    plazo_ejecucion: "",
    ud_base: "",
    usuario_nombre: "Luis",
    especies: [],
    numero_expte: "275/2022",
    tipo_contrato: "privado",
    organo_contratacion: "Alcaldia del Ayuntamiento de Pedro Bernardo",
    forma_oferta: "manual",
    visitado: false,
    favorito: false,
    previewImage: "/img/shared/maps/map_small.png",
    especies_summary: "",
  },
];
